name: simpleproject
description: >-
  Телеграм-бот.
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.13.5
  intl: ^0.17.0
  teledart: ^0.3.4
  telegram_client: ^0.3.55
  yaml: ^3.1.1
  yaml_writer: ^1.0.2
